# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in test_cli.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "open-uri" 
gem "nokogiri" 
gem 'pry'
gem 'bcrypt'